project:
  type: book
  output-dir: docs
  preview:
    browser: false

book:
  title: "From Beta to Meaning: A Guide to Interpreting Regression Analysis"
  author: "Andr√© Walter"
  chapters:
    - index.qmd
    - chapters/Categorical_Compositional.qmd
    - chapters/Interaction_Polynomials.qmd

format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    css: styles.css
