project:
  type: book
  output-dir: docs
  preview:
    browser: false

book:
  title: "But what does it mean?"
  author: "Andr√© Walter"
  chapters:
    - index.qmd
    - preface.qmd
    - chapters/01-introduction.qmd
    - chapters/02-chapter-one.qmd
    - chapters/03-chapter-two.qmd

format:
  html:
    toc: true
    number-sections: true
    html-math-method: mathjax
    css: styles.css
